apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {{`
    kubernetes.azure.com/tls-cert-keyvault-uri: "{{.ingress-tls-cert-keyvault-uri}}"
    kubernetes.azure.com/use-osm-mtls: "{{.ingress-use-osm-mtls}}"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |2-

      proxy_ssl_name "default.{{.service-namespace}}.cluster.local";
    nginx.ingress.kubernetes.io/proxy-ssl-secret: kube-system/osm-ingress-client-cert
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
  name: {{service-name}}
  namespace: {{service-namespace}}
  labels:
    kubernetes.azure.com/generator: {{.GENERATORLABEL}}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - host: "{{.ingress-host}}"
    http:
      paths:
      - backend:
          service:
            name: "{{.service-name}}"
            port:
              number: "{{.service-port}}"
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "{{.ingress-host}}"
    secretName: "keyvault-{{.service-name}}"
  `}}