apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: "{{ .Config.GetVariableValue "ingress-tls-cert-keyvault-uri"}}"
    kubernetes.azure.com/use-osm-mtls: "{{ .Config.GetVariableValue "ingress-use-osm-mtls"}}"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |2-

      proxy_ssl_name "default.{{ .Config.GetVariableValue "service-namespace"}}.cluster.local";
    nginx.ingress.kubernetes.io/proxy-ssl-secret: kube-system/osm-ingress-client-cert
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
  name: "{{ .Config.GetVariableValue "service-name"}}"
  namespace: "{{ .Config.GetVariableValue "service-namespace"}}"
  labels:
    kubernetes.azure.com/generator: {{ .Config.GetVariableValue "GENERATORLABEL"}}
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: "{{ .Config.GetVariableValue "ingress-host"}}"
      http:
        paths:
          - backend:
              service:
                name: "{{ .Config.GetVariableValue "service-name"}}"
                port:
                  number: {{ .Config.GetVariableValue "service-port"}}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "{{ .Config.GetVariableValue "ingress-host"}}"
      secretName: "keyvault-{{ .Config.GetVariableValue "service-name"}}"