apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: "{{index . "ingress-tls-cert-keyvault-uri"}}"
    kubernetes.azure.com/use-osm-mtls: "{{index . "ingress-use-osm-mtls"}}"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/configuration-snippet: |2-

      proxy_ssl_name "default.{{.service-namespace}}.cluster.local";
    nginx.ingress.kubernetes.io/proxy-ssl-secret: kube-system/osm-ingress-client-cert
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
  name: "{{index . "service-name"}}"
  namespace: "{{index . "service-namespace"}}"
  labels:
    kubernetes.azure.com/generator: "{{index . "GENERATORLABEL"}}"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: "{{index . "ingress-host"}}"
      http:
        paths:
          - backend:
              service:
                name: "{{index . "service-name"}}"
                port:
                  number: {{index . "service-port"}}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "{{index . "ingress-host"}}"
      secretName: "keyvault-{{index . "service-name"}}"