Test-Path -Path ./deployTypes/helm -PathType Leaf
Test-Path -Path ./deployTypes/helm/draft.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/Chart.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/helmignore -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/deployment.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/NOTES.txt -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/ingress.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/tests -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/tests/test-connection.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/service.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/serviceaccount.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/templates/helpers.tpl -PathType Leaf
Test-Path -Path ./deployTypes/helm/charts/values.yaml -PathType Leaf
Test-Path -Path ./deployTypes/helm/skaffold.yaml -PathType Leaf
