variables:
  - name: "PORT"
    description: "the port exposed in the application"
  - name: "APPNAME"
    description: "the name of the application"
  - name: "SERVICEPORT"
    description: "the port the service uses to make the application accessible from outside the cluster"
variableDefaults:
  - name: "PORT"
    value: 80
  - name: "SERVICEPORT"
    value: 80