templateName: "deployment-helm"
description: "This template is used to create a Helm deployment for an application"
type: "deployment"
variables:
  - name: "PORT"
    type: "int"
    kind: "port"
    default:
      value: 80
    description: "the port exposed in the application"
  - name: "APPNAME"
    type: "string"
    kind: "kubernetesResourceName"
    description: "the name of the application"
  - name: "SERVICEPORT"
    type: "int"
    kind: "port"
    default:
      referenceVar: "PORT"
    description: "the port the service uses to make the application accessible from outside the cluster"
  - name: "NAMESPACE"
    type: "string"
    kind: "kubernetesNamespace"
    default:
      value: default
    description: " the namespace to place new resources in"
  - name: "IMAGENAME"
    type: "string"
    kind: "containerImageName"
    default:
      referenceVar: "APPNAME"
    description: "the name of the image to use in the deployment"
  - name: "IMAGETAG"
    type: "string"
    kind: "containerImageVersion"
    default:
      disablePrompt: true
      value: "latest"
    description: "the tag of the image to use in the deployment"
  - name: "GENERATORLABEL"
    type: "string"
    kind: "label"
    default:
      disablePrompt: true
      value: "draft"
    description: "the label to identify who generated the resource"
  - name: "ENVVARIABLES"
    type: "map"
    kind: "environmentVariables"
    description: "environment variables for the application"