templateName: "podDisruptionBudget-manifest"
description: "This template is used to create a PodDisruptionBudget for an application"
type: "podDisruptionBudget"
variables:
  - name: "APPNAME"
    type: "string"
    kind: "kubernetesResourceName"
    description: "the name of the application"
  - name: "PARTOF"
    type: "string"
    kind: "label"
    description: "the label to identify which project the resource belong to"
  - name: "GENERATORLABEL"
    type: "string"
    kind: "label"
    description: "the label to identify who generated the resource"
    default:
      value: "draft"
  - name: "MINIMUMREPLICAS"
    type: "int"
    kind: "replicaCount"
    description: "specifies the minimum number of pod replicas that the deployment should have"
    default:
      value: 2
  - name: "MAXIMUMREPLICAS"
    type: "int"
    kind: "replicaCount"
    description: "defines the maximum number of pod replicas the deployment can scale to"
    default:
      value: 5
  - name: "RESOURCETYPE"
    type: "string"
    kind: "scalingResourceType"
    description: "specifies the resource type (e.g., cpu or memory) to be monitored for scaling"
    default:
      value: "cpu"
  - name: "AVGUTILIZATION"
    type: "int"
    kind: "scalingResourceUtilization"
    description: "specifies the average utilization for the monitored resource, triggering scaling when exceeded"
    default:
      value: 80