apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
    environment: production
    testLabel3: randomlabel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      initContainers:
        - name: my-container-CAI-error
          image: nginx:latest
      containers:
        - name: my-container-CAI-error
          image: nginx:latest