apiVersion: apps/v1 
kind: Deployment
metadata:
 name: {{ .Config.GetVariableValue "APPNAME" }}
 labels:
  app.kubernetes.io/name: {{ .Config.GetVariableValue "APPNAME" }}
  app.kubernetes.io/part-of: {{ .Config.GetVariableValue "APPNAME" }}
  kubernetes.azure.com/generator: {{ .Config.GetVariableValue "GENERATORLABEL" }}
spec:
 replicas: 2
 selector:
  matchLabels:
   app: {{ .Config.GetVariableValue "APPNAME" }}
 template:
  metadata:
   labels:
    app: {{  .Config.GetVariableValue "APPNAME" }}
  spec:
   containers:
    - name: {{ .Config.GetVariableValue "APPNAME" }}
      image: {{ .Config.GetVariableValue "IMAGENAME" }}:{{ .Config.GetVariableValue "IMAGETAG" }}
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      {{- if .IncludeInTemplateVersion ">=0.0.2"}}
      resources:
        limits:
          cpu: {{ .Config.GetVariableValue "CPULIMIT" }}
          memory: {{ .Config.GetVariableValue "MEMLIMIT" }}
        requests:
          cpu: {{ .Config.GetVariableValue "CPUREQ" }}
          memory: {{ .Config.GetVariableValue "MEMREQ" }}
      {{- end}}
      {{- if .IncludeInTemplateVersion ">=0.0.3" }}{{template "Probes" . }}{{end}}
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        capabilities:
        drop:
          - all
        add:
          - SETPCAP
          - MKNOD
          - AUDIT_WRITE
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETGID
          - SETUID
          - NET_BIND_SERVICE
          - SYS_CHROOT
          - SETFCAP
          - SYS_PTRACE
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
            app: {{ .Config.GetVariableValue "APPNAME" }}
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
          app: {{ .Config.GetVariableValue "APPNAME" }}
    hostNetwork: false
    hostIPC: false
    securityContext:
      seccompProfile:
      type: RuntimeDefault

{{- define "Probes"}}
      livenessProbe:
        tcpSocket:
          port: {{ .Config.GetVariableValue "PORT" }}
      readinessProbe:
        tcpSocket:
          port: {{ .Config.GetVariableValue "PORT" }}
        periodSeconds: {{ .Config.GetVariableValue "READINESSPERIOD" }}
        timeoutSeconds: {{ .Config.GetVariableValue "TIMEOUT" }}
        {{- if .IncludeInTemplateVersion ">=0.0.4" }}{{template "ProbeVars" . }}{{- end}}
{{- end}}
{{- define "ProbeVars"}}
        initialDelaySeconds: {{ .Config.GetVariableValue "INITIALDELAY" }}
        successThreshold: {{ .Config.GetVariableValue "SUCCESSTHRESHOLD" }} 
        failureThreshold: {{ .Config.GetVariableValue "FAILURETHRESHOLD" }}
{{- end}}