set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

#
# 2) differing output - Some programs produce different output each time
# they run.  The "date" command is an obvious example.  Another is
# ftp, if it produces throughput statistics at the end of a file
# transfer.  If this causes a problem, delete these patterns or replace
# them with wildcards.  An alternative is to use the -p flag (for
# "prompt") which makes Expect only look for the last line of output
# (i.e., the prompt).  The -P flag allows you to define a character to
# toggle this mode off and on.
#
# Read the man page for more info.
#
# -Don


set timeout -1
spawn draftv2 -v create ./test/go
match_max 100000
expect -exact "\[37mDEBU\[0m\[0000\] number of args passed: 1                     \r
\[36mINFO\[0m\[0000\] detecting language                           \r
\[37mDEBU\[0m\[0000\] with file: ./test/go                         \r
\[37mDEBU\[0m\[0000\] ./test/go is 128 bytes                       \r
\[37mDEBU\[0m\[0000\] with file: test/go/go.mod                    \r
\[37mDEBU\[0m\[0000\] test/go/go.mod is 58 bytes                   \r
\[37mDEBU\[0m\[0000\] reading contents of test/go/go.mod           \r
\[37mDEBU\[0m\[0000\] test/go/go.mod got language hints: \[\]string{\"Modula-2\", \"XML\", \"AMPL\", \"Linux Kernel Module\"} \r
\[37mDEBU\[0m\[0000\] test/go/go.mod got result by data:  XML      \r
\[37mDEBU\[0m\[0000\] with file: test/go/main.go                   \r
\[37mDEBU\[0m\[0000\] test/go/main.go is 599 bytes                 \r
\[37mDEBU\[0m\[0000\] test/go/main.go got result by name:  Go      \r
\[37mDEBU\[0m\[0000\] language: XML percent: 8.828006 color: #0060ac \r
\[37mDEBU\[0m\[0000\] language: Go percent: 91.171994 color: #00ADD8 \r
\[37mDEBU\[0m\[0000\] linguist.ProcessDir(./test/go) result:\r
\r
Error: <nil> \r
\[37mDEBU\[0m\[0000\] Go:	91.171994 (#00ADD8)                      \r
\[37mDEBU\[0m\[0000\] XML:	8.828006 (#0060ac)                      \r
\[36mINFO\[0m\[0000\] --> Draft detected Go (91.171994%)           \r
\[?25l\[2K\r\[1m\[31m✗\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m █\r
\[J\[2K\r "
send -- "8"
expect -exact "\[J\[2K\r8\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 8█\r
8\[J\[2K\r "
send -- "0"
expect -exact "\[J\[2K\r0\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 80█\r
0\[J\[2K\r "
send -- "8"
expect -exact "\[J\[2K\r8\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 808█\r
8\[J\[2K\r "
send -- "0"
expect -exact "\[J\[2K\r0\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 8080█\r
0\[J\[2K\r "
send -- "\r"
expect -exact "\[J\[2K\r \[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 8080█\r
\[1A\[2K\r\[2K\r\[2mPlease Enter the port exposed in the application\[0m\[2m:\[0m 8080\r
\[?25h\[37mDEBU\[0m\[0004\] replacing PORT with 8080                     \r
\[37mDEBU\[0m\[0004\] checking name override for srcPath: builders/go/Dockerfile, destPath: ./test/go/Dockerfile, destPrefix: ./test/go/ \r
\[37mDEBU\[0m\[0004\] initializing nameOverrideMap                 \r
\[37mDEBU\[0m\[0004\] mapping path: dockerignore, to prefix .      \r
\[37mDEBU\[0m\[0004\] replacing PORT with 8080                     \r
\[37mDEBU\[0m\[0004\] checking name override for srcPath: builders/go/dockerignore, destPath: ./test/go/dockerignore, destPrefix: ./test/go/ \r
\[37mDEBU\[0m\[0004\] overriding file: ./test/go/dockerignore with prefix: . \r
\[?25l\[2K\r\[2mUse the arrow keys to navigate:\[0m \[2m↓\[0m \[2m↑\[0m \[2m→\[0m \[2m←\[0m \r
\[2K\r\[34m?\[0m Select k8s Deployment Type: \r
\[2K\r  \[1m▸\[0m \[4mhelm\[0m\r
\[2K\r    kustomize\r
\[2K\r    manifests\r
\[J\[2K\r "
send -- "\r"
expect -exact "\[J\[2K\r \[J\[2K\r \[1A\[2K\r\[1A\[2K\r\[1A\[2K\r\[1A\[2K\r\[1A\[2K\r\[2K\r\[32m\[32m✔\[0m \[2mhelm\[0m\r
\[?25h\[J\[2K\r\[?25l\[2K\r\[1m\[31m✗\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m █\r
\[J\[2K\r "
send -- "8"
expect -exact "\[J\[2K\r8\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 8█\r
8\[J\[2K\r "
send -- "0"
expect -exact "\[J\[2K\r0\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 80█\r
0\[J\[2K\r "
send -- "8"
expect -exact "\[J\[2K\r8\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 808█\r
8\[J\[2K\r "
send -- "0"
expect -exact "\[J\[2K\r0\[J\[2K\r\[1A\[2K\r\[2K\r\[1m\[32m✔\[0m \[1mPlease Enter the port exposed in the application\[0m\[1m:\[0m 8080█\r
0\[J\[2K\r "
send -- "\r"
expect eof
