templateName: "azure-pipeline-manifest"
description: "Azure Pipeline for deploying a containerized application to AKS using kubernetes manifests"
type: "workflow"
variables:
  - name: "PIPELINENAME"
    type: "string"
    kind: "workflowName"
    default:
      value: "Build and deploy an app to AKS"
    description: "the name of the azure pipeline"
  - name: "BRANCHNAME"
    type: "string"
    kind: "repositoryBranch"
    default:
      value: "main"
    description: "the branch to trigger the pipeline"
  - name: "ARMSERVICECONNECTION"
    type: "string"
    kind: "azureServiceConnection"
    description: "the name of the Azure Resource Manager service connection"
  - name: "AZURECONTAINERREGISTRY"
    type: "string"
    kind: "azureContainerRegistry"
    description: "the name of the Azure Container Registry"
  - name: "CONTAINERNAME"
    type: "string"
    kind: "containerImageName"
    description: "the container image name"
  - name: "CLUSTERRESOURCEGROUP"
    type: "string"
    kind: "azureResourceGroup"
    description: "the AKS cluster resource group"
  - name: "ACRRESOURCEGROUP"
    type: "string"
    kind: "azureResourceGroup"
    description: "the ACR resource group"
  - name: "CLUSTERNAME"
    type: "string"
    kind: "azureManagedCluster"
    description: "the AKS cluster name"
  - name: "MANIFESTPATH"
    type: "string"
    kind: "dirPath"
    default:
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  - name: "NAMESPACE"
    type: "string"
    kind: "kubernetesNamespace"
    default:
      value: "default"
    description: "the Kubernetes namespace"
