# Azure Kubernetes Service pipeline
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service cluster

variables:
  armServiceConnection: {{ .Config.GetVariableValue "ARMSERVICECONNECTION" }}
  azureContainerRegistry: {{ .Config.GetVariableValue "AZURECONTAINERREGISTRY" }}
  containerName: {{ .Config.GetVariableValue "CONTAINERNAME" }}
  clusterRg: {{ .Config.GetVariableValue "CLUSTERRESOURCEGROUP" }}
  acrRg: {{ .Config.GetVariableValue "ACRRESOURCEGROUP" }}
  clusterName: {{ .Config.GetVariableValue "CLUSTERNAME" }}
  manifestPath: {{ .Config.GetVariableValue "MANIFESTPATH" }}
  namespace: {{ .Config.GetVariableValue "NAMESPACE" }}
  buildContextPath: {{ .Config.GetVariableValue "BUILDCONTEXTPATH" }}
  dockerfile: {{ .Config.GetVariableValue "DOCKERFILE" }}
  tag: "$(Build.BuildId)"
  vmImageName: "ubuntu-latest"
  resourceType: {{ .Config.GetVariableValue "CLUSTERRESOURCETYPE" }}

name: {{ .Config.GetVariableValue "PIPELINENAME" }}

trigger:
  - {{ .Config.GetVariableValue "BRANCHNAME" }}
{{`
stages:
  - stage: BuildAndPush
    displayName: Build stage
    jobs:
      - job: BuildAndPush
        displayName: Build and push image
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureCLI@2
            displayName: Build and push image to Azure Container Registry
            inputs:
              azureSubscription: $(armServiceConnection)
              scriptType: "bash"
              scriptLocation: "inlineScript"
              inlineScript: |
                az acr build --image $1.azurecr.io/$2:$3 --registry $1 -g $4 -f $5 $6
              arguments: "$(azureContainerRegistry) $(containerName) $(tag) $(acrRg) $(dockerfile) $(buildContextPath)"

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: Deploy to AKS
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: KubeloginInstaller@0
          - task: KubernetesManifest@1
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: "deploy"
              connectionType: "azureResourceManager"
              azureSubscriptionConnection: $(armServiceConnection)
              azureResourceGroup: $(clusterRg)
              kubernetesCluster: $(clusterName)
              manifests: $(manifestPath)
              namespace: $(namespace)
              resourceType: $(resourceType)
              containers: |
                $(azureContainerRegistry).azurecr.io/$(containerName):$(tag)
`}}