apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APPNAME}}
  labels:
    app: {{APPNAME}}
spec:
  template:
    spec:
      containers:
        - name: {{APPNAME}}
          image: {{APPNAME}}