apiVersion: v1
kind: Service
metadata:
  name: {{APPNAME}}
  namespace: {{NAMESPACE}}
spec:
  type: LoadBalancer
  selector:
    app: {{APPNAME}}
  ports:
    - protocol: TCP
      port: {{SERVICEPORT}}
      targetPort: {{PORT}}