variables:
  - name: "BRANCHNAME"
    description: "the Github branch to automatically deploy from"
  - name: "RESOURCEGROUP"
    description: "the ACR resource group"
  - name: "AZURECONTAINERREGISTRY"
    description: "the Azure container registry name"
  - name: "CONTAINERNAME"
    description: "the container image name"
  - name: "CLUSTERNAME"
    description: "the AKS cluster name"
  - name: "DEPLOYMENTMANIFESTPATH"
    default: 
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  - name: "BUILDCONTEXTPATH"
    default: 
      value: "."
    description: "the path to the Docker build context"