variables:
  - name: "WORKFLOWNAME"
    default:
      value: "Build and deploy an app to AKS"
    description: "the name of the workflow"
  - name: "BRANCHNAME"
    description: "the Github branch to automatically deploy from"
    resource: "ghBranch"
  - name: "ACRRESOURCEGROUP"
    description: "the ACR resource group"
    resource: "azResourceGroup"
  - name: "AZURECONTAINERREGISTRY"
    description: "the Azure container registry name"
    resource: "azContainerRegistry"
  - name: "CONTAINERNAME"
    description: "the container image name"
    resource: "containerName"
  - name: "CLUSTERRESOURCEGROUP"
    description: "the AKS cluster resource group"
    resource: "azResourceGroup"
  - name: "CLUSTERNAME"
    description: "the AKS cluster name"
    resource: "azClusterName"
  - name: "DEPLOYMENTMANIFESTPATH"
    default: 
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  - name: "DOCKERFILE"
    default:
      value: "./Dockerfile"
    description: "the path to the Dockerfile"
    resource: "dir"
  - name: "BUILDCONTEXTPATH"
    default: 
      value: "."
    description: "the path to the Docker build context"
    resource: "dir"
  - name: "NAMESPACE"
    default:
      value: "default"
    description: "the Kubernetes namespace"
    resource: "namespace"