variables:
  BRANCHNAME:
    description: "the Github branch to automatically deploy from"
  RESOURCEGROUP:
    description: "the ACR resource group"
  AZURECONTAINERREGISTRY:
    description: "the Azure container registry name"
  CONTAINERNAME:
    description: "the container image name"
  CLUSTERNAME:
    description: "the AKS cluster name"
  DEPLOYMENTMANIFESTPATH:
    default: 
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  BUILDCONTEXTPATH:
    default: 
      value: "."
    description: "the path to the Docker build context"