variables:
  BRANCHNAME:
    description: "the Github branch to automatically deploy from"
  RESOURCEGROUP:
    description: "the ACR resource group"
  AZURECONTAINERREGISTRY:
    description: "the Azure container registry name"
  CONTAINERNAME:
    description: "the container image name"
  CLUSTERNAME:
    description: "the AKS cluster name"
  DEPLOYMENTMANIFESTPATH:
    default: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
    disablePrompt: true
  BUILDCONTEXTPATH:
    default: "."
    description: "the path to the Docker build context"