variables:
  BRANCHNAME:
    description: "the Github branch to automatically deploy from"
  ACRRESOURCEGROUP:
    description: "the ACR resource group"
  AZURECONTAINERREGISTRY:
    description: "the Azure container registry name"
  CONTAINERNAME:
    description: "the container image name"
    resource: "containerName"
  CLUSTERRESOURCEGROUP:
    description: "the AKS cluster resource group"
  CLUSTERNAME:
    description: "the AKS cluster name"
  DEPLOYMENTMANIFESTPATH:
    default: 
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  DOCKERFILE:
    default:
      disablePrompt: true
      value: "./Dockerfile"
    description: "the path to the Dockerfile"
  BUILDCONTEXTPATH:
    default: 
      value: "."
    description: "the path to the Docker build context"