variables:
  - name: "WORKFLOWNAME"
    default:
      value: "Build and deploy an app to AKS"
    description: "the name of the workflow"
  - name: "BRANCHNAME"
    description: "the Github branch to automatically deploy from"
    resource: "ghBranch"
  - name: "ACRRESOURCEGROUP"
    description: "the Azure container registry's resource group"
    resource: "azResourceGroup"
  - name: "AZURECONTAINERREGISTRY"
    description: "the Azure container registry's name"
    resource: "azContainerRegistry"
  - name: "ACRREPOSITORYNAME"
    description: "the ACR repository's name for your container image"
    resource: "azAcrRepositoryName"
  - name: "CLUSTERRESOURCEGROUP"
    description: "the Kubernetes cluster's resource group"
    resource: "azResourceGroup"
  - name: "CLUSTERNAME"
    description: "the Kubernetes cluster's name"
    resource: "azClusterName"
  - name: "DEPLOYMENTMANIFESTPATH"
    default: 
      disablePrompt: true
      value: "./manifests"
    description: "the path to the Kubernetes deployment manifest"
  - name: "DOCKERFILEPATH"
    default:
      value: "./Dockerfile"
    description: "the path to the Dockerfile"
    resource: "path"
  - name: "BUILDCONTEXTPATH"
    default: 
      value: "."
    description: "the path to the Docker build context"
    resource: "path"
  - name: "NAMESPACE"
    default:
      value: "default"
    description: "the Kubernetes namespace"
    resource: "azNamespace"
  - name: "PRIVATECLUSTER"
    default:
      value: false
    description: "true if the AKS cluster is private"
    type: "bool"