apiVersion: v1
kind: Service
metadata:
  name: {{.APPNAME}}
  namespace: {{.NAMESPACE}}
  labels:
    kubernetes.azure.com/generator: {{.GENERATORLABEL}}
spec:
  type: LoadBalancer
  selector:
    app: {{.APPNAME}}
  ports:
    - protocol: TCP
      port: {{.SERVICEPORT}}
      targetPort: {{.PORT}}