image:
  repository: "{{ .Config.GetVariableValue "IMAGENAME" }}"
  tag: "{{ .Config.GetVariableValue "IMAGETAG" }}"
  pullPolicy: "{{ .Config.GetVariableValue "IMAGEPULLPOLICY" }}"
service:
  annotations: {}
  type: LoadBalancer
  port: "{{ .Config.GetVariableValue "SERVICEPORT" }}"
