image:
  repository: "{{ .Config.GetVariableValue "APPNAME" }}"
  pullPolicy: Always
  tag: "latest"
service:
  annotations: {}
  type: LoadBalancer
  port: "{{ .Config.GetVariableValue "SERVICEPORT" }}"
