apiVersion: v1
kind: ConfigMap
metadata:
  name: envvars-configmap
data:
  {{- if .Values.envVariables }}
    {{- range $key, $value := .Values.envVariables }}
    - name: {{ $key }}
      value: {{ $value | quote }}
  {{- end }}
  {{- else }}
    # No environment variables provided
  {{- end }}