{{- if ne .Values.namespace "default" }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    openservicemesh.io/monitored-by: osm
    kubernetes.azure.com/generator: {{ .Values.generatorlabel }}
  annotations:
    openservicemesh.io/sidecar-injection: enabled
  {{- end }}