name: Draft Defaults Smoke Test
on:
  pull_request:
    branches: [ main ]

jobs:
#  Validate that `create` can successfully execute with default values
  create-defaults-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.2
      - name: make
        run: make
      - name: Validate Create Runs with Defaults
        run: |
          yes 2>/dev/null | ./draft