name: Draft Info Integration Test
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "./src"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2
      - name: make
        run: |
          cd src
          make
      - run: |
          ./draft info > ./info.json
          ls
          pwd
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./src/test/integration/info_json_schema.json
          jsons: ./src/info.json