name: Install Script Integration Test
on:
  pull_request:
    branches: [ main ]

jobs:
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Install Script 
        run: ./scripts/install.sh
      - name: Validate Command is Installed
        run: |
          if ! command -v draft &> /dev/null
          then
              echo "draft could not be found"
              exit 1
          fi
      - name: Validate Draft Command Runs
        run: draft -h