name: Install Script Integration Test
on:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Install Script 
        run: ./scripts/install.sh
      - name: Validate Command is Installed
        run: |
          if ! command -v draft &> /dev/null
          then
              echo "draft could not be found"
              exit 1
          fi