name: Poll Starter Workflows

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  STARTER_WORKFLOW_PATH: "./starterWorkflows/"
  STARTER_WORKFLOW_REPO_BRANCH: "partner_templates"

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create new run information
        run: |
          echo "Creating new run information record"
          declare -A seenWorkflows
          touch /tmp/seenWorkflows
          declare -p seenWorkflows > /tmp/seenWorkflows

      - name: Download starter workflows
        run: |
          # get previous seen workflows
          source /tmp/seenWorkflows
          seenWorkflows[test]=test

          # get deployment workflows
          echo "Calling GitHub API for starter workflows"
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/actions/starter-workflows/contents/deployments?ref=$STARTER_WORKFLOW_REPO_BRANCH \
            | jq -c '.[]' | while read -r workflow;
          do
            # extract fields
            name=$(echo $workflow | jq '.name' -r)
            downloadUrl=$(echo $workflow | jq '.download_url' -r)
            sha=$(echo $workflow | jq '.sha' -r)
            
            # download workflow if it's an AKS workflow and not seen before
            echo "Checking workflow $name"
            if [[ $name == azure-kubernetes-service* ]] ;
            then
              echo "Downloading starter workflow $name"
              mkdir -p $STARTER_WORKFLOW_PATH && touch $STARTER_WORKFLOW_PATH$name
              wget -O $STARTER_WORKFLOW_PATH$name $downloadUrl
              seenWorkflows["$name"]="$sha"
              echo ${seenWorkflows[*]}
            fi
          done

          # store seen workflows
          echo "Storing run information"
          echo ${seenWorkflows[*]}
          declare -p seenWorkflows > /tmp/seenWorkflows
      - name: Upload run information
        uses: actions/upload-artifact@v3
        with:
          name: seen
          path: /tmp/seenWorkflows
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update starter workflows
          title: Automated Update Starter Workflows
          body: This is an auto-generated PR. The starter workflow repo has changes not in this repository.
          branch: starter-workflow-updates
