name: Draftv2 Releases

on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  Release-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Release Dir
        run: mkdir bin
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Build Release Binaries
        run: make build-all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/*
          token: ${{ secrets.PUBLISH_RELEASE_TOKEN }}
        env:
          GITHUB_REPOSITORY: Azure/aks-app